import { type NextRequest, NextResponse } from "next/server"

// Mock database - same as in route.ts
const mockDatabase: Array<{
  id: number
  title: string
  originalTitle?: string
  type: "Movie" | "TV Show"
  director: string
  budget: string
  location: string
  duration: string
  yearTime: string
  genre?: string
  rating?: number
  description?: string
  videoUrl?: string
  language: string
  country: string
  createdAt: string
  updatedAt: string
}> = [
  // English Content
  {
    id: 1,
    title: "Inception",
    type: "Movie",
    director: "Christopher Nolan",
    budget: "$160M",
    location: "LA, Paris, Tokyo",
    duration: "148 min",
    yearTime: "2010",
    genre: "Sci-Fi Thriller",
    rating: 8.8,
    description: "A thief who steals corporate secrets through dream-sharing technology",
    videoUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    language: "English",
    country: "USA",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    title: "Breaking Bad",
    type: "TV Show",
    director: "Vince Gilligan",
    budget: "$3M/ep",
    location: "Albuquerque, New Mexico",
    duration: "49 min/ep",
    yearTime: "2008-2013",
    genre: "Crime Drama",
    rating: 9.5,
    description: "A chemistry teacher turned methamphetamine manufacturer",
    videoUrl: "https://www.youtube.com/watch?v=HhesaQXLuRY",
    language: "English",
    country: "USA",
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-02T00:00:00Z",
  },
  // Spanish Content
  {
    id: 3,
    title: "Money Heist",
    originalTitle: "La Casa de Papel",
    type: "TV Show",
    director: "Álex Pina",
    budget: "$2M/ep",
    location: "Madrid, Spain",
    duration: "70 min/ep",
    yearTime: "2017-2021",
    genre: "Crime Thriller",
    rating: 8.2,
    description: "A criminal mastermind manipulates hostages and police during a heist at the Royal Mint of Spain",
    videoUrl: "https://www.youtube.com/watch?v=_InqQJRqGW4",
    language: "Spanish",
    country: "Spain",
    createdAt: "2024-01-03T00:00:00Z",
    updatedAt: "2024-01-03T00:00:00Z",
  },
  {
    id: 4,
    title: "Pan's Labyrinth",
    originalTitle: "El Laberinto del Fauno",
    type: "Movie",
    director: "Guillermo del Toro",
    budget: "$19M",
    location: "Spain",
    duration: "118 min",
    yearTime: "2006",
    genre: "Fantasy Drama",
    rating: 8.2,
    description: "A young girl escapes into a fantasy world during the Spanish Civil War",
    videoUrl: "https://www.youtube.com/watch?v=EqYiSlkvRuw",
    language: "Spanish",
    country: "Spain/Mexico",
    createdAt: "2024-01-04T00:00:00Z",
    updatedAt: "2024-01-04T00:00:00Z",
  },
  // French Content
  {
    id: 5,
    title: "Amélie",
    originalTitle: "Le Fabuleux Destin d'Amélie Poulain",
    type: "Movie",
    director: "Jean-Pierre Jeunet",
    budget: "$10M",
    location: "Paris, France",
    duration: "122 min",
    yearTime: "2001",
    genre: "Romantic Comedy",
    rating: 8.3,
    description: "A shy waitress decides to help those around her find happiness",
    videoUrl: "https://www.youtube.com/watch?v=MhkNbOWimgM",
    language: "French",
    country: "France",
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-01-05T00:00:00Z",
  },
  {
    id: 6,
    title: "Call My Agent!",
    originalTitle: "Dix Pour Cent",
    type: "TV Show",
    director: "Fanny Herrero",
    budget: "$1.5M/ep",
    location: "Paris, France",
    duration: "52 min/ep",
    yearTime: "2015-2020",
    genre: "Comedy Drama",
    rating: 8.3,
    description: "The daily lives of talent agents at a Parisian agency",
    videoUrl: "https://www.youtube.com/watch?v=8B9dXNl4xeE",
    language: "French",
    country: "France",
    createdAt: "2024-01-06T00:00:00Z",
    updatedAt: "2024-01-06T00:00:00Z",
  },
  // German Content
  {
    id: 7,
    title: "Dark",
    type: "TV Show",
    director: "Baran bo Odar",
    budget: "$3M/ep",
    location: "Berlin, Germany",
    duration: "60 min/ep",
    yearTime: "2017-2020",
    genre: "Sci-Fi Mystery",
    rating: 8.7,
    description: "A time travel conspiracy spans several generations in a German town",
    videoUrl: "https://www.youtube.com/watch?v=rrwycJ08PSA",
    language: "German",
    country: "Germany",
    createdAt: "2024-01-07T00:00:00Z",
    updatedAt: "2024-01-07T00:00:00Z",
  },
  {
    id: 8,
    title: "The Lives of Others",
    originalTitle: "Das Leben der Anderen",
    type: "Movie",
    director: "Florian Henckel von Donnersmarck",
    budget: "$2M",
    location: "Berlin, Germany",
    duration: "137 min",
    yearTime: "2006",
    genre: "Drama Thriller",
    rating: 8.4,
    description: "A Stasi agent becomes obsessed with the lives of a writer and his lover",
    videoUrl: "https://www.youtube.com/watch?v=n3_iLOp6IhM",
    language: "German",
    country: "Germany",
    createdAt: "2024-01-08T00:00:00Z",
    updatedAt: "2024-01-08T00:00:00Z",
  },
  // Japanese Content
  {
    id: 9,
    title: "Spirited Away",
    originalTitle: "千と千尋の神隠し",
    type: "Movie",
    director: "Hayao Miyazaki",
    budget: "$19M",
    location: "Tokyo, Japan",
    duration: "125 min",
    yearTime: "2001",
    genre: "Animation Fantasy",
    rating: 9.2,
    description: "A girl enters a world ruled by gods and witches where humans are changed into beasts",
    videoUrl: "https://www.youtube.com/watch?v=ByXuk9QqQkk",
    language: "Japanese",
    country: "Japan",
    createdAt: "2024-01-09T00:00:00Z",
    updatedAt: "2024-01-09T00:00:00Z",
  },
  {
    id: 10,
    title: "Attack on Titan",
    originalTitle: "進撃の巨人",
    type: "TV Show",
    director: "Tetsuro Araki",
    budget: "$500K/ep",
    location: "Tokyo, Japan",
    duration: "24 min/ep",
    yearTime: "2013-2023",
    genre: "Animation Action",
    rating: 9.0,
    description: "Humanity fights for survival against giant humanoid Titans",
    videoUrl: "https://www.youtube.com/watch?v=LHtdKWJdif4",
    language: "Japanese",
    country: "Japan",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
  // Korean Content
  {
    id: 11,
    title: "Parasite",
    originalTitle: "기생충",
    type: "Movie",
    director: "Bong Joon-ho",
    budget: "$11M",
    location: "Seoul, South Korea",
    duration: "132 min",
    yearTime: "2019",
    genre: "Thriller Drama",
    rating: 8.5,
    description: "A poor family schemes to become employed by a wealthy family",
    videoUrl: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
    language: "Korean",
    country: "South Korea",
    createdAt: "2024-01-11T00:00:00Z",
    updatedAt: "2024-01-11T00:00:00Z",
  },
  {
    id: 12,
    title: "Squid Game",
    originalTitle: "오징어 게임",
    type: "TV Show",
    director: "Hwang Dong-hyuk",
    budget: "$2.4M/ep",
    location: "Seoul, South Korea",
    duration: "60 min/ep",
    yearTime: "2021-present",
    genre: "Survival Drama",
    rating: 8.0,
    description: "Desperate contestants play deadly children's games for a massive cash prize",
    videoUrl: "https://www.youtube.com/watch?v=oqxAJKy0ii4",
    language: "Korean",
    country: "South Korea",
    createdAt: "2024-01-12T00:00:00Z",
    updatedAt: "2024-01-12T00:00:00Z",
  },
  // Chinese Content
  {
    id: 13,
    title: "Crouching Tiger, Hidden Dragon",
    originalTitle: "臥虎藏龍",
    type: "Movie",
    director: "Ang Lee",
    budget: "$17M",
    location: "Beijing, China",
    duration: "120 min",
    yearTime: "2000",
    genre: "Martial Arts Drama",
    rating: 7.9,
    description: "A young Chinese warrior steals a sword from a famed swordsman",
    videoUrl: "https://www.youtube.com/watch?v=YhCHw0Ovqf4",
    language: "Chinese",
    country: "China/Taiwan",
    createdAt: "2024-01-13T00:00:00Z",
    updatedAt: "2024-01-13T00:00:00Z",
  },
  {
    id: 14,
    title: "The Untamed",
    originalTitle: "陈情令",
    type: "TV Show",
    director: "Chen Jialin",
    budget: "$1M/ep",
    location: "Hengdian, China",
    duration: "45 min/ep",
    yearTime: "2019",
    genre: "Fantasy Romance",
    rating: 8.8,
    description: "Two soulmates navigate a world of cultivation and supernatural beings",
    videoUrl: "https://www.youtube.com/watch?v=lE2yz7hj3IM",
    language: "Chinese",
    country: "China",
    createdAt: "2024-01-14T00:00:00Z",
    updatedAt: "2024-01-14T00:00:00Z",
  },
  // Hindi Content
  {
    id: 15,
    title: "3 Idiots",
    type: "Movie",
    director: "Rajkumar Hirani",
    budget: "$6.7M",
    location: "Delhi, India",
    duration: "170 min",
    yearTime: "2009",
    genre: "Comedy Drama",
    rating: 8.4,
    description: "Two friends search for their long-lost companion who inspired them to think differently",
    videoUrl: "https://www.youtube.com/watch?v=K0eDlFX9GMc",
    language: "Hindi",
    country: "India",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: 16,
    title: "Sacred Games",
    type: "TV Show",
    director: "Anurag Kashyap",
    budget: "$1.5M/ep",
    location: "Mumbai, India",
    duration: "50 min/ep",
    yearTime: "2018-2019",
    genre: "Crime Thriller",
    rating: 8.6,
    description: "A policeman receives a call from a gangster who tells him he has 25 days to save Mumbai",
    videoUrl: "https://www.youtube.com/watch?v=ua5WZ0g69wM",
    language: "Hindi",
    country: "India",
    createdAt: "2024-01-16T00:00:00Z",
    updatedAt: "2024-01-16T00:00:00Z",
  },
  // Italian Content
  {
    id: 17,
    title: "Life is Beautiful",
    originalTitle: "La Vita è Bella",
    type: "Movie",
    director: "Roberto Benigni",
    budget: "$20M",
    location: "Tuscany, Italy",
    duration: "116 min",
    yearTime: "1997",
    genre: "Comedy Drama",
    rating: 8.6,
    description: "A Jewish father uses humor to shield his son from the horrors of a Nazi concentration camp",
    videoUrl: "https://www.youtube.com/watch?v=pAYEQP8gx3w",
    language: "Italian",
    country: "Italy",
    createdAt: "2024-01-17T00:00:00Z",
    updatedAt: "2024-01-17T00:00:00Z",
  },
  {
    id: 18,
    title: "Gomorrah",
    originalTitle: "Gomorra",
    type: "TV Show",
    director: "Stefano Sollima",
    budget: "$2M/ep",
    location: "Naples, Italy",
    duration: "50 min/ep",
    yearTime: "2014-2021",
    genre: "Crime Drama",
    rating: 8.6,
    description: "The story of the Neapolitan crime organization and the infighting for control",
    videoUrl: "https://www.youtube.com/watch?v=g3sK5EvWcP4",
    language: "Italian",
    country: "Italy",
    createdAt: "2024-01-18T00:00:00Z",
    updatedAt: "2024-01-18T00:00:00Z",
  },
  // Russian Content
  {
    id: 19,
    title: "Leviathan",
    originalTitle: "Левиафан",
    type: "Movie",
    director: "Andrey Zvyagintsev",
    budget: "$2M",
    location: "Murmansk, Russia",
    duration: "140 min",
    yearTime: "2014",
    genre: "Drama",
    rating: 7.6,
    description: "A man fights against corruption and injustice in a small Russian town",
    videoUrl: "https://www.youtube.com/watch?v=3bJuY7zMBzY",
    language: "Russian",
    country: "Russia",
    createdAt: "2024-01-19T00:00:00Z",
    updatedAt: "2024-01-19T00:00:00Z",
  },
  {
    id: 20,
    title: "Better Than Us",
    originalTitle: "Лучше, чем люди",
    type: "TV Show",
    director: "Andrey Junkovsky",
    budget: "$1M/ep",
    location: "Moscow, Russia",
    duration: "48 min/ep",
    yearTime: "2018-2019",
    genre: "Sci-Fi Drama",
    rating: 7.2,
    description: "A family's life changes when they acquire an advanced android",
    videoUrl: "https://www.youtube.com/watch?v=Pp3OfJ9wHmU",
    language: "Russian",
    country: "Russia",
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
  },
  // Hindi Content
  {
    id: 21,
    title: "Dangal",
    type: "Movie",
    director: "Nitesh Tiwari",
    budget: "$9.5M",
    location: "Haryana, India",
    duration: "161 min",
    yearTime: "2016",
    genre: "Biographical Sports Drama",
    rating: 8.4,
    description: "A former wrestler trains his two daughters to become world-class wrestlers.",
    videoUrl: "https://www.youtube.com/watch?v=x_7YlGv9u1g",
    language: "Hindi",
    country: "India",
    createdAt: "2024-01-21T00:00:00Z",
    updatedAt: "2024-01-21T00:00:00Z",
  },
  {
    id: 22,
    title: "Gangs of Wasseypur",
    type: "Movie",
    director: "Anurag Kashyap",
    budget: "$840K",
    location: "Jharkhand, India",
    duration: "321 min (in 2 parts)",
    yearTime: "2012",
    genre: "Action Crime Drama",
    rating: 8.2,
    description: "A clash between Sultan and Shahid Khan leads to a blood feud spanning three generations.",
    videoUrl: "https://www.youtube.com/watch?v=TOiQeJygY0c",
    language: "Hindi",
    country: "India",
    createdAt: "2024-01-22T00:00:00Z",
    updatedAt: "2024-01-22T00:00:00Z",
  },
  {
    id: 23,
    title: "Queen",
    type: "Movie",
    director: "Vikas Bahl",
    budget: "$400K",
    location: "Delhi & Paris",
    duration: "146 min",
    yearTime: "2013",
    genre: "Comedy Drama",
    rating: 8.2,
    description: "A Delhi girl embarks on her honeymoon alone after her fiancé cancels their wedding.",
    videoUrl: "https://www.youtube.com/watch?v=KGC6vl3lzf0",
    language: "Hindi",
    country: "India",
    createdAt: "2024-01-23T00:00:00Z",
    updatedAt: "2024-01-23T00:00:00Z",
  },
  {
    id: 24,
    title: "PK",
    type: "Movie",
    director: "Rajkumar Hirani",
    budget: "$13M",
    location: "Delhi, India",
    duration: "153 min",
    yearTime: "2014",
    genre: "Comedy Drama",
    rating: 8.1,
    description: "An alien lands on Earth and befriends a journalist, questioning religious dogmas.",
    videoUrl: "https://www.youtube.com/watch?v=o_vESNL3t4Y",
    language: "Hindi",
    country: "India",
    createdAt: "2024-01-24T00:00:00Z",
    updatedAt: "2024-01-24T00:00:00Z",
  },
  {
    id: 25,
    title: "Bajrangi Bhaijaan",
    type: "Movie",
    director: "Kabir Khan",
    budget: "$13M",
    location: "Delhi, India",
    duration: "159 min",
    yearTime: "2015",
    genre: "Action Comedy Drama",
    rating: 8.0,
    description: "A man with a golden heart helps a mute Pakistani girl return to her homeland.",
    videoUrl: "https://www.youtube.com/watch?v=o7ufQMjAl0M",
    language: "Hindi",
    country: "India",
    createdAt: "2024-01-25T00:00:00Z",
    updatedAt: "2024-01-25T00:00:00Z",
  },
  {
    id: 26,
    title: "Andhadhun",
    type: "Movie",
    director: "Sriram Raghavan",
    budget: "$4.3M",
    location: "Pune, India",
    duration: "139 min",
    yearTime: "2018",
    genre: "Black Comedy Crime Thriller",
    rating: 8.2,
    description: "A blind pianist gets entangled in a murder.",
    videoUrl: "https://www.youtube.com/watch?v=i-pPreLUBi8",
    language: "Hindi",
    country: "India",
    createdAt: "2024-01-26T00:00:00Z",
    updatedAt: "2024-01-26T00:00:00Z",
  },
  {
    id: 27,
    title: "Talvar",
    type: "Movie",
    director: "Meghna Gulzar",
    budget: "$4M",
    location: "Noida, India",
    duration: "132 min",
    yearTime: "2015",
    genre: "Crime Drama Thriller",
    rating: 8.1,
    description: "An investigation into the murder of a teenage girl unveils multiple conflicting stories.",
    videoUrl: "https://www.youtube.com/watch?v=yrJLWDYXPfQ",
    language: "Hindi",
    country: "India",
    createdAt: "2024-01-27T00:00:00Z",
    updatedAt: "2024-01-27T00:00:00Z",
  },
  {
    id: 28,
    title: "Article 15",
    type: "Movie",
    director: "Anubhav Sinha",
    budget: "$4M",
    location: "Uttar Pradesh, India",
    duration: "130 min",
    yearTime: "2019",
    genre: "Crime Drama Thriller",
    rating: 8.2,
    description: "An IPS officer investigates the disappearance of three girls from a small village.",
    videoUrl: "https://www.youtube.com/watch?v=HKJuPpP-vjI",
    language: "Hindi",
    country: "India",
    createdAt: "2024-01-28T00:00:00Z",
    updatedAt: "2024-01-28T00:00:00Z",
  },
  {
    id: 29,
    title: "Special 26",
    type: "Movie",
    director: "Neeraj Pandey",
    budget: "$6M",
    location: "Mumbai, India",
    duration: "144 min",
    yearTime: "2013",
    genre: "Crime Thriller",
    rating: 7.9,
    description: "A group of con artists pose as CBI officers to rob politicians and businessmen.",
    videoUrl: "https://www.youtube.com/watch?v=JGlau9-0J8Q",
    language: "Hindi",
    country: "India",
    createdAt: "2024-01-29T00:00:00Z",
    updatedAt: "2024-01-29T00:00:00Z",
  },
  {
    id: 30,
    title: "Pink",
    type: "Movie",
    director: "Aniruddha Roy Chowdhury",
    budget: "$3M",
    location: "Delhi, India",
    duration: "136 min",
    yearTime: "2016",
    genre: "Crime Drama Thriller",
    rating: 8.1,
    description: "Three young women fight for justice after being sexually assaulted by a group of influential men.",
    videoUrl: "https://www.youtube.com/watch?v=AL2lkj89cb4",
    language: "Hindi",
    country: "India",
    createdAt: "2024-01-30T00:00:00Z",
    updatedAt: "2024-01-30T00:00:00Z",
  },
  {
    id: 31,
    title: "Delhi Crime",
    type: "TV Show",
    director: "Richie Mehta",
    budget: "$400K/ep",
    location: "Delhi, India",
    duration: "45-60 min/ep",
    yearTime: "2019-present",
    genre: "Crime Drama",
    rating: 8.5,
    description: "A dramatized account of the investigation into the 2012 Delhi gang rape case.",
    videoUrl: "https://www.youtube.com/watch?v=ctBcnEaOUJ4",
    language: "Hindi",
    country: "India",
    createdAt: "2024-01-31T00:00:00Z",
    updatedAt: "2024-01-31T00:00:00Z",
  },
  {
    id: 32,
    title: "Mirzapur",
    type: "TV Show",
    director: "Gurmmeet Singh",
    budget: "$200K/ep",
    location: "Mirzapur, India",
    duration: "40-50 min/ep",
    yearTime: "2018-present",
    genre: "Action Crime Thriller",
    rating: 8.4,
    description: "A tale of drugs, guns, and lawlessness in the town of Mirzapur.",
    videoUrl: "https://www.youtube.com/watch?v=wCFyrgI3RQs",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
  {
    id: 33,
    title: "Panchayat",
    type: "TV Show",
    director: "Deepak Kumar Mishra",
    budget: "$100K/ep",
    location: "Uttar Pradesh, India",
    duration: "30-40 min/ep",
    yearTime: "2020-present",
    genre: "Comedy Drama",
    rating: 8.8,
    description: "An engineering graduate reluctantly takes a job as a Panchayat secretary in a remote village.",
    videoUrl: "https://www.youtube.com/watch?v=mojZJ7Kmex8",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-02T00:00:00Z",
    updatedAt: "2024-02-02T00:00:00Z",
  },
  {
    id: 34,
    title: "Kota Factory",
    type: "TV Show",
    director: "Raghav Subbu",
    budget: "$80K/ep",
    location: "Kota, India",
    duration: "30-40 min/ep",
    yearTime: "2019-present",
    genre: "Comedy Drama",
    rating: 9.0,
    description: "The life of students in Kota, the coaching hub of India.",
    videoUrl: "https://www.youtube.com/watch?v=9WZuWz83otI",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-03T00:00:00Z",
    updatedAt: "2024-02-03T00:00:00Z",
  },
  {
    id: 35,
    title: "Aspirants",
    type: "TV Show",
    director: "Apoorv Singh Karki",
    budget: "$90K/ep",
    location: "Delhi, India",
    duration: "30-40 min/ep",
    yearTime: "2021",
    genre: "Drama",
    rating: 8.6,
    description: "The story of three UPSC aspirants and their struggles.",
    videoUrl: "https://www.youtube.com/watch?v=oLkk09Bm_DY",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-04T00:00:00Z",
    updatedAt: "2024-02-04T00:00:00Z",
  },
  {
    id: 36,
    title: "Gullak",
    type: "TV Show",
    director: "Shreyansh Pandey",
    budget: "$70K/ep",
    location: "Uttar Pradesh, India",
    duration: "20-30 min/ep",
    yearTime: "2019-present",
    genre: "Comedy Drama",
    rating: 9.1,
    description: "The Mishra family's everyday adventures and misadventures.",
    videoUrl: "https://www.youtube.com/watch?v=Nw_B0zafiY4",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-05T00:00:00Z",
    updatedAt: "2024-02-05T00:00:00Z",
  },
  {
    id: 37,
    title: "Scam 1992",
    type: "TV Show",
    director: "Hansal Mehta",
    budget: "$250K/ep",
    location: "Mumbai, India",
    duration: "45-60 min/ep",
    yearTime: "2020",
    genre: "Biographical Crime Drama",
    rating: 9.3,
    description:
      "The story of Harshad Mehta, a stockbroker who single-handedly took the stock market to dizzying heights.",
    videoUrl: "https://www.youtube.com/watch?v=NFK9-kVAytA",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-06T00:00:00Z",
    updatedAt: "2024-02-06T00:00:00Z",
  },
  {
    id: 38,
    title: "The Family Man",
    type: "TV Show",
    director: "Raj Nidimoru",
    budget: "$300K/ep",
    location: "Mumbai, India",
    duration: "40-50 min/ep",
    yearTime: "2019-present",
    genre: "Action Comedy Drama",
    rating: 8.6,
    description: "A middle-class man secretly works as an intelligence officer for the T.A.S.C.",
    videoUrl: "https://www.youtube.com/watch?v=ddlILA1U1Q4",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-07T00:00:00Z",
    updatedAt: "2024-02-07T00:00:00Z",
  },
  {
    id: 39,
    title: "Asur: Welcome to Your Dark Side",
    type: "TV Show",
    director: "Oni Sen",
    budget: "$150K/ep",
    location: "Varanasi, India",
    duration: "40-50 min/ep",
    yearTime: "2020-present",
    genre: "Crime Thriller Mystery",
    rating: 8.5,
    description: "A forensic expert returns to his roots to hunt down a serial killer.",
    videoUrl: "https://www.youtube.com/watch?v=EQtc1s1vJ2E",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-08T00:00:00Z",
    updatedAt: "2024-02-08T00:00:00Z",
  },
  {
    id: 40,
    title: "Breathe",
    type: "TV Show",
    director: "Mayank Sharma",
    budget: "$120K/ep",
    location: "Mumbai, India",
    duration: "40-50 min/ep",
    yearTime: "2018-present",
    genre: "Crime Drama Thriller",
    rating: 8.3,
    description: "A desperate father makes immoral choices to save his son's life.",
    videoUrl: "https://www.youtube.com/watch?v=fvgFWegEdmE",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-09T00:00:00Z",
    updatedAt: "2024-02-09T00:00:00Z",
  },
  {
    id: 41,
    title: "Bard of Blood",
    type: "TV Show",
    director: "Ribhu Dasgupta",
    budget: "$180K/ep",
    location: "Balochistan, Pakistan",
    duration: "35-45 min/ep",
    yearTime: "2019",
    genre: "Action Thriller Spy",
    rating: 7.2,
    description: "An ex-spy must rescue his captured colleagues from Balochistan.",
    videoUrl: "https://www.youtube.com/watch?v=jJ5yK7qiKrc",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-10T00:00:00Z",
    updatedAt: "2024-02-10T00:00:00Z",
  },
  {
    id: 42,
    title: "Rangbaaz",
    type: "TV Show",
    director: "Bhav Dhulia",
    budget: "$100K/ep",
    location: "Rajasthan, India",
    duration: "30-40 min/ep",
    yearTime: "2018-present",
    genre: "Crime Thriller",
    rating: 7.8,
    description: "The story of a gangster from Uttar Pradesh.",
    videoUrl: "https://www.youtube.com/watch?v=j3I-cZFuapI",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-11T00:00:00Z",
    updatedAt: "2024-02-11T00:00:00Z",
  },
  {
    id: 43,
    title: "Inside Edge",
    type: "TV Show",
    director: "Karan Anshuman",
    budget: "$200K/ep",
    location: "Mumbai, India",
    duration: "40-50 min/ep",
    yearTime: "2017-present",
    genre: "Sports Drama",
    rating: 8.0,
    description: "Power, money, and fame meet in the world of cricket.",
    videoUrl: "https://www.youtube.com/watch?v=jBT4jGqKcpQ",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-12T00:00:00Z",
    updatedAt: "2024-02-12T00:00:00Z",
  },
  {
    id: 44,
    title: "Jamtara - Sabka Number Ayega",
    type: "TV Show",
    director: "Soumendra Padhi",
    budget: "$90K/ep",
    location: "Jamtara, India",
    duration: "30-40 min/ep",
    yearTime: "2020-present",
    genre: "Crime Drama",
    rating: 7.3,
    description: "Youngsters run a lucrative phishing operation from Jamtara.",
    videoUrl: "https://www.youtube.com/watch?v=B-D_EQK_iCQ",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-13T00:00:00Z",
    updatedAt: "2024-02-13T00:00:00Z",
  },
  {
    id: 45,
    title: "She",
    type: "TV Show",
    director: "Arif Ali",
    budget: "$110K/ep",
    location: "Mumbai, India",
    duration: "30-40 min/ep",
    yearTime: "2020-present",
    genre: "Crime Drama Thriller",
    rating: 6.8,
    description: "An undercover assignment changes a female constable's life.",
    videoUrl: "https://www.youtube.com/watch?v=vJY3mt6fdwk",
    language: "Hindi",
    country: "India",
    createdAt: "2024-02-14T00:00:00Z",
    updatedAt: "2024-02-14T00:00:00Z",
  },
  // Italian Content
  {
    id: 17,
    title: "Life is Beautiful",
    originalTitle: "La Vita è Bella",
    type: "Movie",
    director: "Roberto Benigni",
    budget: "$20M",
    location: "Tuscany, Italy",
    duration: "116 min",
    yearTime: "1997",
    genre: "Comedy Drama",
    rating: 8.6,
    description: "A Jewish father uses humor to shield his son from the horrors of a Nazi concentration camp",
    videoUrl: "https://www.youtube.com/watch?v=pAYEQP8gx3w",
    language: "Italian",
    country: "Italy",
    createdAt: "2024-01-17T00:00:00Z",
    updatedAt: "2024-01-17T00:00:00Z",
  },
  {
    id: 18,
    title: "Gomorrah",
    originalTitle: "Gomorra",
    type: "TV Show",
    director: "Stefano Sollima",
    budget: "$2M/ep",
    location: "Naples, Italy",
    duration: "50 min/ep",
    yearTime: "2014-2021",
    genre: "Crime Drama",
    rating: 8.6,
    description: "The story of the Neapolitan crime organization and the infighting for control",
    videoUrl: "https://www.youtube.com/watch?v=g3sK5EvWcP4",
    language: "Italian",
    country: "Italy",
    createdAt: "2024-01-18T00:00:00Z",
    updatedAt: "2024-01-18T00:00:00Z",
  },
  // Russian Content
  {
    id: 19,
    title: "Leviathan",
    originalTitle: "Левиафан",
    type: "Movie",
    director: "Andrey Zvyagintsev",
    budget: "$2M",
    location: "Murmansk, Russia",
    duration: "140 min",
    yearTime: "2014",
    genre: "Drama",
    rating: 7.6,
    description: "A man fights against corruption and injustice in a small Russian town",
    videoUrl: "https://www.youtube.com/watch?v=3bJuY7zMBzY",
    language: "Russian",
    country: "Russia",
    createdAt: "2024-01-19T00:00:00Z",
    updatedAt: "2024-01-19T00:00:00Z",
  },
  {
    id: 20,
    title: "Better Than Us",
    originalTitle: "Лучше, чем люди",
    type: "TV Show",
    director: "Andrey Junkovsky",
    budget: "$1M/ep",
    location: "Moscow, Russia",
    duration: "48 min/ep",
    yearTime: "2018-2019",
    genre: "Sci-Fi Drama",
    rating: 7.2,
    description: "A family's life changes when they acquire an advanced android",
    videoUrl: "https://www.youtube.com/watch?v=Pp3OfJ9wHmU",
    language: "Russian",
    country: "Russia",
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
  },
]

function validateEntry(data: any) {
  const errors: string[] = []

  if (!data.title || typeof data.title !== "string" || data.title.trim().length === 0) {
    errors.push("Title is required")
  }

  if (!data.type || !["Movie", "TV Show"].includes(data.type)) {
    errors.push("Type must be either 'Movie' or 'TV Show'")
  }

  if (!data.director || typeof data.director !== "string" || data.director.trim().length === 0) {
    errors.push("Director is required")
  }

  if (!data.budget || typeof data.budget !== "string" || data.budget.trim().length === 0) {
    errors.push("Budget is required")
  }

  if (!data.location || typeof data.location !== "string" || data.location.trim().length === 0) {
    errors.push("Location is required")
  }

  if (!data.duration || typeof data.duration !== "string" || data.duration.trim().length === 0) {
    errors.push("Duration is required")
  }

  if (!data.yearTime || typeof data.yearTime !== "string" || data.yearTime.trim().length === 0) {
    errors.push("Year/Time is required")
  }

  if (!data.language || typeof data.language !== "string" || data.language.trim().length === 0) {
    errors.push("Language is required")
  }

  if (!data.country || typeof data.country !== "string" || data.country.trim().length === 0) {
    errors.push("Country is required")
  }

  if (data.rating !== undefined && (typeof data.rating !== "number" || data.rating < 0 || data.rating > 10)) {
    errors.push("Rating must be a number between 0 and 10")
  }

  return errors
}

// GET - Fetch single entry
export async function GET(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params
    const entryId = Number.parseInt(id)

    const entry = mockDatabase.find((e) => e.id === entryId)

    if (!entry) {
      return NextResponse.json({ error: "Entry not found" }, { status: 404 })
    }

    return NextResponse.json(entry)
  } catch (error) {
    return NextResponse.json({ error: "Failed to fetch entry" }, { status: 500 })
  }
}

// PUT - Update entry
export async function PUT(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params
    const entryId = Number.parseInt(id)
    const data = await request.json()

    // Validate input
    const validationErrors = validateEntry(data)
    if (validationErrors.length > 0) {
      return NextResponse.json({ error: "Validation failed", details: validationErrors }, { status: 400 })
    }

    const entryIndex = mockDatabase.findIndex((e) => e.id === entryId)

    if (entryIndex === -1) {
      return NextResponse.json({ error: "Entry not found" }, { status: 404 })
    }

    // Update entry
    const updatedEntry = {
      ...mockDatabase[entryIndex],
      title: data.title.trim(),
      originalTitle: data.originalTitle?.trim() || undefined,
      type: data.type,
      director: data.director.trim(),
      budget: data.budget.trim(),
      location: data.location.trim(),
      duration: data.duration.trim(),
      yearTime: data.yearTime.trim(),
      genre: data.genre?.trim() || undefined,
      rating: data.rating || undefined,
      description: data.description?.trim() || undefined,
      videoUrl: data.videoUrl?.trim() || undefined,
      language: data.language.trim(),
      country: data.country.trim(),
      updatedAt: new Date().toISOString(),
    }

    mockDatabase[entryIndex] = updatedEntry

    return NextResponse.json(updatedEntry)
  } catch (error) {
    return NextResponse.json({ error: "Failed to update entry" }, { status: 500 })
  }
}

// DELETE - Delete entry
export async function DELETE(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params
    const entryId = Number.parseInt(id)

    const entryIndex = mockDatabase.findIndex((e) => e.id === entryId)

    if (entryIndex === -1) {
      return NextResponse.json({ error: "Entry not found" }, { status: 404 })
    }

    // Remove entry from database
    const deletedEntry = mockDatabase.splice(entryIndex, 1)[0]

    return NextResponse.json({
      message: "Entry deleted successfully",
      deletedEntry,
    })
  } catch (error) {
    return NextResponse.json({ error: "Failed to delete entry" }, { status: 500 })
  }
}
